### ISSUE TITLE
Register extension on Packagist.org

### ISSUE THREAD

**Issue by igrizzli** [php-ds/extension#10]
Register package on packagist for installation via composer.
It can be used for highlights in IDE in dev environment.

**Comment by rtheunissen** [comment]
@igrizzli The extension will be hosted and installed from PECL at some point, and the PHP implementation will be available through Packagist. :+1: 

See #8

**Comment by linden2015** [comment]
@rtheunissen ,

I notice packagist has up to version 1.2.0 whereas this Github repo has 1.2.4

* How are the versionings synced with the compiled php extensions?
* What caused the delay between Github and Packagist, and can this be fixed?
