### ISSUE TITLE
Consider removing constructor from the Ds\Sequence interface.

### ISSUE THREAD

**Issue by lelgaunt** [php-ds/extension#100]
The Ds\Sequence interface declares rather meaningless constructor with a single optional argument thus preventing users from implementing it properly. Interfaces in OOP are intended to describe an API and should not carry any information specific for object instantiation.

I understand that the main purpose of these data structures is not to be extended in client application, yet still there are some use-cases where implementing these interfaces in user-defined classes makes sense (e.g. performing a type control for items in sequence, which would require declaring a 'type' parameter in constructor).

**Comment by rtheunissen** [comment]
I agree completely, the constructor should not be part of the interface. 👍
