### ISSUE TITLE
Cannot use [] syntax on Win10 PHP 7.1

### ISSUE THREAD

**Issue by keikland** [php-ds/extension#102]
Loading x86 NTS v1.2.3 php_ds.dll into php 7.1.10 on Win10 64 seems to go fine.  After instantiating a vector object, allocating it to desired size, and setting a value, however, I immediately get an error.  This is the code:
            $_MemVec=new \Ds\Vector(); 
            $_MemVec->allocate($_Size+1);
            $_MemVec[0] = $default;

$_Size is > 700.  The debugger says that the [] syntax is not supported.  The parallel code for standard arrays works fine.

Any guidance?

Kjell

**Comment by rtheunissen** [comment]
Hi @keikland, I somehow missed this issue. 😞 

That syntax is definitely supported and shouldn't be causing an issue. Does it work if you don't allocate?

**Comment by rtheunissen** [comment]
@keikland what's the status here?

**Comment by keikland** [comment]
Hi,
Sorry about not reverting.  I ended up having to attack this in a different way temporarily.  Also did some speed tests that showed that v7+ does quite well with native arrays.  I am stuck in some other work temporarily, and it will take some days before I can get back to working on that code.

Best regards,
Kjell

**Comment by rtheunissen** [comment]
I'll close this issue for now as there hasn't been further discussion.
