### ISSUE TITLE
PHP_DS_NS macro doesn't appear to resolve correctly on return types

### ISSUE THREAD

**Issue by dktapps** [php-ds/extension#104]
I'm using PHP 7.2.0RC5, and observing some odd return typehints when running `php --re ds`, such as the following in `\Ds\Collection`:

```
       Method [ <internal:ds> abstract public method copy ] {

          - Parameters [0] {
          }
          - Return [ PHP_DS_NS(Collection) or NULL ]
        }
```
I encountered this issue while trying to generate IDE stubs for the extension. Parameter typehints aren't affected - only return typehints.

Platform: Windows 10 1703 64-bit
PHP: 7.2.0RC5 ZTS
DS: http://windows.php.net/downloads/pecl/snaps/ds/1.2.3/php_ds-1.2.3-7.2-ts-vc15-x64.zip

**Comment by rtheunissen** [comment]
I'll take a look at this today. You can always use the polyfill/composer package for stubs.

**Comment by rtheunissen** [comment]
Same issue on OS X

**Comment by rtheunissen** [comment]
@krakjoe might need your help on this one, I don't know why the macro isn't being evaluated. Found this (https://stackoverflow.com/a/17596812/828867) but if that's true then I'm not sure why the PHP_DS_NS macro works fine when defining the class via `INIT_CLASS_ENTRY`.
