### ISSUE TITLE
\Ds\Sequence::find() should be aware of Hashable

### ISSUE THREAD

**Issue by trebi** [php-ds/extension#107]
Right now, the implementation uses `array_search(..., ..., true)` with strict check enabled, which of course compares object references ignoring the fact that they might equal according to `Hashable::equals()`.

This is quite confusing, as for instance `Set` is aware of this interface:

```php
$foo = new class implements Hashable {
	public function hash() { return 'hash'; }
	public function equals($obj): bool { return true; }
};

$map = new Map;
$map[0] = new $foo;
$map[1] = new $foo;

var_dump($map->values()->contains(new $foo)); // bool(false)
var_dump((new \Ds\Set($map->values()))->contains(new $foo)); // bool(true)
// in my opinion, both should return true
```

What do you think? How should this behavior be addressed?

Thanks!
Richard

**Comment by rtheunissen** [comment]
I'll attempt to address this issue in 2.0, potentially by splitting equality from hashing. The `Hashable` interface's `equals` acts in the context of **using the object as a key**. This is not the case for `Sequence`.

This should really be at the language level (overridable equality). 😢

**Comment by trebi** [comment]
Sounds like creating `Equalable` interface is the most sane solution in this case :-/

**Comment by rtheunissen** [comment]
I agree it's inconsistent and should be fixed. The solution I have in mind is discussed here: https://github.com/php-ds/extension/issues/67#issuecomment-343611975
