### ISSUE TITLE
Packagist doesn't have the latest release from Github

### ISSUE THREAD

**Issue by linden2015** [php-ds/extension#108]
I notice packagist has up to version 1.2.0 whereas this Github repo has 1.2.4

* How are the versionings synced with the compiled php extensions?
* What caused the delay between Github and Packagist, and can this be fixed?

**Comment by rtheunissen** [comment]
The extension (1.2.4) is not on packagist, but the polyfill (1.2.0) is. The extension is installed with PECL. Both share the same API (1.2.x), but the polyfill has had a few patches in the meantime.
