### ISSUE TITLE
[Request] Provide interfaces for final classes to make mocking possible

### ISSUE THREAD

**Issue by peios** [php-ds/extension#109]
When writing unit tests, it is often convenient to just mock any dependency of a piece of code in order to achieve complete isolation and to be able to really test out single units in complex scenarios. 

This simplifies testing a lot in cases in which it is desirable not to go through the construction process of the object to be tested: one may simply disable the constructor and manually set the specific properties by using, for example, Reflection.

As an example, if I need to verify that a method, after having processed a parameter, adds the processed value to an underlying `Map`, I could just do something like the following:

```php
class ComplexClassTest extends TestCase
{
    // include something to be able to access protected properties via reflection
    // by invoking a method that we'll name "setProperty()"
    // let's pretend that this "something" is a trait
    use SetPropertyTrait;

    public function testSomethingWorks()
    {
        // we create the object to test by disabling the constructor, 
        // but we don't mock out any method
        $obj = $this->getMockBuilder(ComplexClass::class)
            ->disableOriginalConstructor()
            ->setMethods(null)
            ->getMock();

        // we mock the \Ds\Map dependency and take control of 
        // the \Ds\Map::put() method
        $map = $this->getMockBuilder(\Ds\Map::class)
            ->setMethods(['put'])
            ->getMock();

        // we setup our expectations for the test
        $map->expects(static::once())
            ->method('put')
            ->with(static::equalTo('my processed parameter'));

        // we manually set the value of the protected property 
        // ComplexClass::$map to the mock \Ds\Map we created
        $this->setProperty($obj, 'map', $map);

        // and invoke our method to verify our expectations
        $obj->callMethodWhichPutsSomethingOnTheMap('my parameter');
    }
}
```

By doing something like this, I can simply verify that the `callMethodWhichPutsSomethingOnTheMap` does what it must do, without having to possibly inject 3 or 4 objects via the constructor of my `ComplexClass` object.

The issue here is: `\Ds\Map` is declared `final`. As such, PHPUnit cannot mock it, since its mocking mechanism is based on (kind of) extending the class. For context, [Mockery can kind of do that](http://docs.mockery.io/en/latest/reference/final_methods_classes.html), by setting up a proxy. I just believe it is a bit overkill to (ab)use dependency managers like Composer to include random components simply to be able to achieve a simple goal :)

Would you consider either removing the `final` declaration, or providing a matching interface (e.g.: `MapInterface`)? This is not needed from a functional point of view, the extension works well without it.

I understand you points (both) of not providing interfaces for everything you wrote, since there is not much space to play with alternative implementations, and of making some classes final, since this was meant to encourage composition over brainless, infinite inheritance, and I am fine with a "no", I just want to highlight this issue and see what you think about it :)

I'm not providing version or installation information since this is not needed for this question.

If you need further information, just ask, I'll be on it!

**Comment by rtheunissen** [comment]
I like the idea of an interface for each collection. :+1:

That would also allow other implementations to be written that conforms to the same API. One reservation I have is that 2.0 will see capability that you can't implement in userland, so one MapInterface implementation might not behave exactly like the core one. As long as that is documented, I'm sure it should be fine.

**Comment by peios** [comment]
Great! Maybe one might not be able to implement certain capabilities in plain PHP, but it might become interesting in cases of different implementations in C. And it will be handy for testing, which is good!

As you said, as long as the documentation states it clearly, there should not be any issue with it.

And thank you for the quick feedback, btw.

I don't know how you deal with feature requests: I'll leave this issue open just in case, if you prefer to close it just... Close it :)

**Comment by morrisonlevi** [comment]
> As an example, if I need to verify that a method, after having processed a parameter, adds the processed value to an underlying Map [...]

You don't need to mock it for this. Just check the presence of the value in the map after calling the method.

I am also surprised that @rtheunissen is in favor of an interface for each type of collection. I seem to recall a conversation about that when this library was first announced that indicated you saw no point or value to it; what changed?

**Comment by rtheunissen** [comment]
This is one of those cases where I think if you need an interface for each class, you're doing something wrong. I will do my best to avoid these interfaces. However, if there is a valid case where a final class breaks testability, there would be little cost to introduce these interfaces.

**Comment by peios** [comment]
>  You don't need to mock it for this. Just check the presence of the value in the map after calling the method.

Yes, you can definitely do that: I just believe that depending on the fact that `\Ds\Map` (or any other dependency) works as expected is kind of a limitation during unit testing. That's why I was trying to mock it, instead of providing the raw object.

>  I seem to recall a conversation... 

It's also stated in the blog post which describes the extension and its performance.
That's why I opened a feature request :) it is not good to rely on external assumptions when unit testing, so I was exposing the "issue" (which can be worked around, even if not without some little smell) and proposing two possible solutions to that problem :)

**Comment by peios** [comment]
Also, if I have to say: I believe that in case working around this issue is desired, introducing interfaces would still be better than removing the `final` declaration.

This last one is there to highlight an important aspect of the extension, to avoid useless, long-chained inheritance constructs which make up for much more complexity than what is desirable.

**Comment by rtheunissen** [comment]
Removing `final` is not an option here. And I think that external assumptions are fine. We rely on them all the time. Imagine mocking core php classes because we don't trust them to work.

**Comment by nikic** [comment]
I agree with @morrisonlevi. Data structures, similarly to value objects, should not be mocked. If you are mocking Map::put(), what you end up testing are low-level implementation details. You shouldn't care how the value got into the map, you should care that it's in there in the end.

Adding a mess of interfaces to support this (imho) anti-pattern seems like an undesirable trade-off to me.

**Comment by peios** [comment]
>  Data structures, similarly to value objects, should not be mocked

I have to say I usually observe this: my bad for not thinking about it this time. Mocking complex dependencies when testing delicate components is fine, mocking data structures is useless (also, @nikic sorry for having caused you repeat that again, I completely missed the point...).

Also, it could make sense if such structures would be complex to set up, but hey: they barely have a constructor (in PHP userland).

I believe I'm going to close this in a couple of hours if nothing more has to be said: reading from what @nikic stated, it might even be misleading to introduce such interfaces here (and to leave this issue hanging around)!
