### ISSUE TITLE
Why are the classes `final`?

### ISSUE THREAD

**Issue by TheDigitalOrchard** [php-ds/extension#115]
I'm curious why the classes are tagged as `final`?

I'm working on a project where the code will fall-back to `SplObjectStorage` if `Ds\Set` is not available. But these two classes have different methods, such as `attach()` vs `add()`. I would like to be able to extend `Ds\Set` in order to provide a common set of methods so I'm not continually checking which method I should be calling at runtime.

I know there are other creative solutions around this, but being able to extend classes is extremely helpful, and I'm not aware of a reason why a class like `Ds\Set` should be tagged as `final`.

Can anyone enlighten me?

**Comment by rtheunissen** [comment]
See the "Why are all the classes final?" section of the FAQ at the bottom of https://medium.com/@rtheunissen/efficient-data-structures-for-php-7-9dda7af674cd. 

In your case, what you should do is create an interface for the methods you need, and implement two classes for that interface, one which uses `SplObjectStorage` internally and one which uses `Ds\Set` internally. Determine which one to produce based on whether `ds` is loaded.
