### ISSUE TITLE
Alternative construction syntax - keep or let go?

### ISSUE THREAD

**Issue by rtheunissen** [php-ds/extension#18]
There is currently two ways to *construct* a structure:

### Namespaced, using *new*

```php
$map = new \Ds\Map();
```

**Advantages**:
- Expected
- Namespaced

---

### Global namespace, static

```php
$map = ds::map();
```

**Advantages**:
- Can use all structures with `use ds;`.
- Can be chained without enclosing parentheses, ie. no `(new Map())->reverse()`.
- Resembles C++ syntax.

---

Would it be better, for the sake of consistency, to keep to either one or the other? And if so, which?

**Comment by john-wilkinson** [comment]
It should be the first one. 

- The advantages of a static factory do not outweigh the negatives of moving away from having a single way to do something.
- The mechanism to accomplish something must be consistent, and the syntax to create an object is the first example
- If Map implements an interface (and it should), it should probably be called MapInterface.

**Comment by rtheunissen** [comment]
I'm considering an `ini` option for the global namespace pattern.

**Comment by twistor** [comment]
An ini option sounds like a terrible idea.

**Comment by rtheunissen** [comment]
@twistor agreed. 😭

**Comment by krakjoe** [comment]
I think drop the global functions altogether.

**Comment by rtheunissen** [comment]
Removed in fae280ab05f8e07a82720c20129be3240bbc2d9c.

**Comment by krakjoe** [comment]
Excellent ... I should have looked :)
