### ISSUE TITLE
Support road map?

### ISSUE THREAD

**Issue by Tatsh** [php-ds/extension#19]
Wondering what sort of support (both paid and unpaid) you see yourself doing for this repository, unless PHP accepts your extension as-is (or almost as-is).

The reason is because anyone grabbing this today may be taking a risk in doing so, because the PHP implementation does not perform as well as PHP's objects or arrays so it cannot act as an exact replacement, and it may be possible this extension stops working with any major release of PHP in the future like 7.1.

Like any library, there is a risk of deprecation in a large code base and normally such a thing does not get fixed for a while as it 'still works'. The problem is that with PHP extensions the code can simply stop working when a PHP upgrade is nearly required (when PHP 7.0.x gets deprecated) if the API becomes incompatible.

**Comment by rtheunissen** [comment]
@Tatsh I intent to support this project for a very long time, and I suspect that there will be many more contributors when we release a stable version via PECL with documentation.

No paid support at this stage. The PHP implementation is entirely just for compatibility. If the extension stops working for a minor release like 7.1, we'll fix what's broken and release a new minor of the extension.

**Comment by Tatsh** [comment]
Thank you. I will consider using this project.
