### ISSUE TITLE
Removing while iterating

### ISSUE THREAD

**Issue by lilty** [php-ds/extension#20]
New (and awsome) data structures but still php, this should work :yum: 
``` php
<?php
class Foo {
    public $bar;
    public function __construct($bar) {
        $this->bar = $bar;
    }
}

$set = new \Ds\Set;
for ($i = 0; $i<=9; $i++) {
    $set[] = new Foo($i);
}
foreach ($set as $key => $value) {
    echo $value->bar;
}
echo PHP_EOL;
foreach ($set as $key => $value) {
    echo $value->bar;
    $set->remove($value);
}
echo PHP_EOL;
var_dump($set);
```
```
0123456789
01234
object(Ds\Set)#1 (5) {
  [0]=>
  object(class@anonymous)#7 (1) {
    ["bar"]=>
    int(5)
  }
  [1]=>
  object(class@anonymous)#8 (1) {
    ["bar"]=>
    int(6)
  }
  [2]=>
  object(class@anonymous)#9 (1) {
    ["bar"]=>
    int(7)
  }
  [3]=>
  object(class@anonymous)#10 (1) {
    ["bar"]=>
    int(8)
  }
  [4]=>
  object(class@anonymous)#11 (1) {
    ["bar"]=>
    int(9)
  }
}
```

**Comment by rtheunissen** [comment]
You are absolutely right - this does not have the same behaviour as the PHP array, which if I understand correctly updates its own internal traversal pointer during `unset`. I'm still not decided or convinced what to do regarding manipulation during iteration. Java throws a `ConcurrentModificationException`, which should be trivial to implement. The other option is to adjust the iterator's position during a `remove` (not as easy to implement, also adds a small amount of overhead).

I haven't looked at this code in a while (on vacation still) but there will be a solution coming your way. Thanks for bringing this up. 👍 

```php
<?php
class Foo {
    public $bar;
    public function __construct($bar) {
        $this->bar = $bar;
    }
}

$set = [];
for ($i = 0; $i<=9; $i++) {
    $set[] = new Foo($i);
}
foreach ($set as $key => $value) {
    echo $value->bar;
}
echo PHP_EOL;
foreach ($set as $value) {
    if(($key = array_search($value, $set)) !== false) {
        unset($set[$key]);
    }
}
echo PHP_EOL;
var_dump($set);
```

```
0123456789
0123456789
array(0) {
}
```

**Comment by rtheunissen** [comment]
See #17

**Comment by lilty** [comment]
I'm trying to find something fast to write a [LINQ](https://msdn.microsoft.com/en-us/library/bb397926.aspx) php like library, php-ds got me out of programming hell.
Finally i will rewrite it directly in c, benchmark are far of what i expected, php fault.
The php-ds restrictive  approach is quite understandable but in this case (#17) i will suggest a php approach, less flexible. Play with the iterator position is not the best but it's php, don't care :stuck_out_tongue: 
Thanks for your hard work :+1:

**Comment by rtheunissen** [comment]
Closing in favour of #17
