### ISSUE TITLE
Freeze when running xor during equals

### ISSUE THREAD

**Issue by thecrypticace** [php-ds/extension#35]
I've run into a case where I have sets that contain hashable objects which themselves contain sets and hashable objects.<sup>1</sup> The equals function on `\Ds\Hashable` necessitates adding an `equals()` method. To do this I ensure this I xor the two sets and check that the resulting set has no elements.<sup>2</sup> 

However, it appears that this freezes when:
- objects have the same hash.
- AND the objects are checked for equality by their identity using `===`

I've got a test case here. The only reason I didn't PR this one is it is seemingly fragile. I tried porting it over and it didn't fail. Not sure why that is.

```
class PauseTest extends PHPUnit_Framework_TestCase
{
    /** @test */
    public function doesnt_freeze_when_adding_items_to_a_set()
    {
        $a = new Container([new Box(0)]);
        $b = new Container([new Box(0)]);

        new Ds\Set([$a, $b]);
    }
}

final class Container implements Ds\Hashable
{
    public $items;

    public function __construct($items) { $this->items = new Ds\Set($items); }
    public function hash() { return 0; }
    public function equals($obj) : bool { return $this->items->xor($obj->items)->count() === 0; }
}

class Box implements Ds\Hashable
{
    private $id;

    public function __construct($id) { $this->id = $id; }
    public function equals($obj) : bool { return $this === $obj; }
    public function hash() { return $this->id; }
}
```

---
1. Could we have Hashable sets built-in? That'd be awesome!
2. I realize now that this logic is flawed… oops. Hey, at least I found a bug!

**Comment by rtheunissen** [comment]
@thecrypticace what do you mean by Hashable sets built in? Have Set implement Hashable?

**Comment by thecrypticace** [comment]
Yeah.

**Comment by rtheunissen** [comment]
@thecrypticace step through each value and use a combined hash and equals?

**Comment by rtheunissen** [comment]
I ran your code outside of PHPUnit and it doesn't seem to freeze. Did I get your example right?

```php
<?php

final class Container implements Ds\Hashable
{
    public $items;

    public function __construct($items)
    {
        $this->items = new Ds\Set($items);
    }

    public function hash()
    {
        return 0;
    }

    public function equals($obj) : bool
    {
        return $this->items->xor($obj->items)->count() === 0;
    }
}

class Box implements Ds\Hashable
{
    private $id;

    public function __construct($id)
    {
        $this->id = $id;
    }

    public function equals($obj) : bool
    {
        return $this === $obj;
    }

    public function hash()
    {
        return $this->id;
    }
}

$a = new Container([new Box(0)]);
$b = new Container([new Box(0)]);

var_dump(new Ds\Set([$a, $b]));
```

```
object(Ds\Set)#7 (2) {
  [0]=>
  object(Container)#1 (1) {
    ["items"]=>
    object(Ds\Set)#3 (1) {
      [0]=>
      object(Box)#2 (1) {
        ["id":"Box":private]=>
        int(0)
      }
    }
  }
  [1]=>
  object(Container)#4 (1) {
    ["items"]=>
    object(Ds\Set)#6 (1) {
      [0]=>
      object(Box)#5 (1) {
        ["id":"Box":private]=>
        int(0)
      }
    }
  }
}

```

**Comment by thecrypticace** [comment]
That is really strange. I'll see if I can writeup a fully isolated (outside of PHPUnit) test.

**Comment by thecrypticace** [comment]
> step through each value and use a combined hash and equals?

Yeah. The way I'm doing it right now requires that all the contents are objects implementing Hashable but for my uses that is an always valid assumption.

Not sure how it would have to act when containing non-cashable objects or primitives.

**Comment by thecrypticace** [comment]
I've just given you access to a repo so you can see what I'm talking about.

```
src/Structures/Set.php:137
src/Structures/Set.php:148
```

**Comment by thecrypticace** [comment]
I just (as of 2 minutes ago) re-cloned this repo and recompiled everything. It seems the pause is gone.

Whatever it was has been fixed. I guess some build files had gotten left over between builds somehow? Probably a mishap on my part.

**Comment by rtheunissen** [comment]
> Not sure how it would have to act when containing non-cashable objects or primitives.

We would just foreach internally and call `get_hash` for each value.

See https://github.com/php-ds/extension/blob/e04bdc24ba09aeafb2fdc36f6faa919141e93fb8/src/ds/ds_htable.c#L301

**Comment by thecrypticace** [comment]
Ah, I see.
