### ISSUE TITLE
Need more information when showing ds in phpinfo()

### ISSUE THREAD

**Issue by grizzlylab** [php-ds/extension#36]
I compiled and installed the package (as described in README.md). Then I checked phpinfo() and I cannot find any details about ds (except it is enabled).
![phpinfo-ds](https://cloud.githubusercontent.com/assets/2612537/17456361/6cce3918-5bd5-11e6-9d4a-b2fba276c829.png)

**Comment by nikic** [comment]
What additional information should it show?

**Comment by castarco** [comment]
+1

I think showing version info is interesting because the APIs could change. I know that the API is stable... but eventually a 2.0 version will be released with backwards-incompatible changes :p .

**Comment by rtheunissen** [comment]
I like the version idea. Eg

```
json

json support => enabled
json version => 1.4.0
```

**Comment by rtheunissen** [comment]
Added in 6a4a1d9f221a71eb47b4299983f3f5f667b7768d
