### ISSUE TITLE
`find` should return null when a value could not be found, instead of false

### ISSUE THREAD

**Issue by rtheunissen** [php-ds/extension#44]
This applies to all current and future variations of `find`.

**Comment by morrisonlevi** [comment]
`Deque` has a find; what else? I seem to remember some docs for this ext but can't seem to find them anymore.

**Comment by morrisonlevi** [comment]
Ah, docs are on [php.net now](http://docs.php.net/manual/en/book.ds.php). Will look into this.

**Comment by morrisonlevi** [comment]
I think I've fixed everything I can find (ha) about it.

**Comment by rtheunissen** [comment]
I've actually changed my mind on this. `find` should support an optional default value and throw an exception if the key couldn't be found and no default was provided. So if you know you have string keys you can use `$map->find(5, false)` which would return `false` if a key for the value `5` couldn't be found. This allows us to not be ambiguous by returning `null` or `false` when those two values *could* have been used as keys. It's up to the developer to establish an appropriate "not found" value. A side effect of this is that it imitates how `get(key, default)` works, only in reverse.
