### ISSUE TITLE
final classes and extend

### ISSUE THREAD

**Issue by basz** [php-ds/extension#54]
Hi,

Is there a compeling reason to make all classes final? It makes it hard to do this; 

```
class SomeSet extends Set
{
...
}

function someFunction(SomeSet $set) {
...
} 
```
I know I can do composition over inheritance to create VO that use ds internally
```
class SomeSet
{
  private $set;
  
  function  __construct($values)
  {
    $this->set = new Set($values);
  }
  ... more methods exposing $this->set. 
}
```
I've looked into class_alias but that only works with user provided classes

**Comment by rtheunissen** [comment]
What's a use case for extending?

**Comment by nikic** [comment]
@rtheunissen Design concerns notwithstanding, allowing people to extend classes that implement custom object handlers is a major PITA. You'll have to ensure that everything is still working correctly if something like offsetGet() is overwritten. This means checking whether the method was extended inside the handler and falling back to the default behavior in that case. This is expensive, either in terms of performance or memory (SPL adds something like 5 function pointers to each structure to deal with this). There's also lots of fun to be hard with discrepancies between what an internal handler can do (think fetch modes) vs what a userland handler can do, as well as those cases where people override only one method like offsetHas() without also overriding offsetGet(), which requires special consideration when handling BP_VAR_IS read_dimensions, ... etc.

**Comment by basz** [comment]
My concerns purely come from a DDD Ubiquitous Language standpoint.
