### ISSUE TITLE
Needing stub for autocompletion

### ISSUE THREAD

**Issue by pickbreaker** [php-ds/extension#70]
I´m using phpStorm for writing on a bigger website. Therefor i need a stub of this PHP extension to enable autocompletion and error Detection. Extension works fine!

Thanks in advance
pickbreaker

**Comment by castarco** [comment]
I think that more info is needed. Which classes and/or methods are not auto-completing?

You can install the polyfill with Composer without problems (the extension will be used, not the polyfill, and if you want, you can install the polyfill as a development dependency). The polyfill will trigger the PHPStorm autocompletion.

**Comment by rtheunissen** [comment]
@castarco with the perfect answer. Require the polyfill but install the extension. The extension makes the classes available on load so no classes need to be autoloaded, but PHPStorm will pick up the class files in your vendor directory.

**Comment by pickbreaker** [comment]
Thanks
