### ISSUE TITLE
Consider porting the "\array_fill" method to the PHP-DS api (as static factory)

### ISSUE THREAD

**Issue by castarco** [php-ds/extension#71]
It would be awesome to have a static factory for Deque and Vector instances to initialize instances with a default length and value.

This will be much faster (and cleaner) than the following alternatives:

1. Passing a pre-constructed array (we'll code less, and we'll use less memory): 
```php
$v = new \Ds\Vector(\array_fill(0, 100, 1));
```

2. Creating an empty vector, preallocating, and iterating:
```php
$v = new \Ds\Vector();
$v->allocate(100);
for($i=0; $i<100; $i++) {
    $v->push(1);
}
```

Something like this, would be better (in my opinion):
```php
$v = \Ds\Vector::fill(100, 1);
```

Of course, the method name (and other details) can be discussed, I think that my proposal isn't optimal.

P.D.: I know that Vector can disappear in the following library versions, I used this class only as an example.

**Comment by rtheunissen** [comment]
What about an instance method? Create a new, empty collection, then fill.

**Comment by castarco** [comment]
This would work too. If you prefer to avoid static factories then is a good way to go.
But I have some doubts about the best way to implement it.
  * The method should mutate the state of the object where has been called? Or return a new instance?
  * If we mutate the object's state, should we return a reference to the mutated object? or declare the method as `void`?
  * And more important. What happens if we call the method on a previously initialized instance?

**Comment by rtheunissen** [comment]
> The method should mutate the state of the object where has been called? Or return a new instance?

I would expect it to mutate the instance, yes.

> If we mutate the object's state, should we return a reference to the mutated object? or declare the method as void?

`void` 

> What happens if we call the method on a previously initialized instance?

Good question, which comes down to the interface/API.

What about something like this:

```php
public function fill(int $start, int $num, mixed $value): void;
```

Depending on the structure, this would effectively be an overwrite from `$start` for a length `$num` with value `$value`. So if you had a `Sequence` of `[a, b, c, d]` and you called `$sequence->fill(2, 3, 'x')` it would yield `[a, b, x, x, x]`. I wonder if `write` would be a better name for this because it's not technically a *fill*. 

Something that *fill* could be is:

```php
public function fill(mixed $value, int $num = null): void;
```

This would fill from the start for a given length, or the current size of the sequence if `$num` is not provided. So effectively the same as `write(0, count($sequence), $value)`. If you wanted to fill an empty sequence you would use `fill($value, $count)`.

**Comment by castarco** [comment]
I like the proposed method signature. But I think that even if `fill` isn't the best possible name, it's a little bit better than `write`... mainly because `write` is too generic and the intent is to write a single value over many positions.

**Comment by castarco** [comment]
P.D.: Should I try to implement the method? Where's the best place? The 2.0 branch? or could be in the 1.x versions?

**Comment by castarco** [comment]
There's another point that should be considered.

Imagine we have a Sequence '$s' that verifies `$s->count() === 10`, and we try to call something like `$s->fill(15, 100, 33.56)` ... what should happen with the positions `10, 11, 12, 13, and 14`?

**Comment by rtheunissen** [comment]
I don't think fill should have a starting index. See the very last header mentioned above.

**Comment by castarco** [comment]
It feels like a good tradeoff :smile: , I'd like to contribute the implementation of this method... where should I start? (If you like the idea, of course)

**Comment by rtheunissen** [comment]
I like the idea. :) Let's implement it on Sequence. Start with 2.0 branch on the polyfill and 2.0 on tests, then the extension.

**Comment by rtheunissen** [comment]
This is now part of the draft for 2.0 👍
