### ISSUE TITLE
Surprising (bad) benchmark results...

### ISSUE THREAD

**Issue by castarco** [php-ds/extension#72]
Hello,

Since I'm developing an extension to work with matrix, and tensors, and in first place I have to develop a pure PHP prototype, I've benchmarked some combinations to find the best one... and I did find that `Ds\Vector` performs consistently worse than `array` on sequential accesses...

Here is the gist with the benchmark:
https://gist.github.com/castarco/5b051f9e7df04a2de87d3268f01ea461

**UPDATE :** Here a gist processing the results:
https://gist.github.com/castarco/8591dc20e2740215709ede9566eaa826

The results are commented in the gist. I've tried to avoid measuring initialization, and to repeat the tests many times to smooth the potential "noise". I'd like to hear your opinion about the benchmark, because I'm suspicious of having did something wrong.

**Comment by castarco** [comment]
Here a "cleaner" benchmark, explicitly testing read, write, and a combination of both:
https://gist.github.com/castarco/0987d06b2b3baf55903be09b34d9bb0a

**Comment by nikic** [comment]
Assuming vector has no particular inefficiencies in its implementation, this is not entirely unexpected. A packed array is behaviorally similar to a vector, but the code-path for it is much more optimized. The advantage of the vector here would be lower memory usage.

**Comment by castarco** [comment]
@nikic , the "lack" of optimization for the `Ds` code paths... are a matter of dedicated programmer hours? or an impossibility due to the interaction between the PHP's core and the extensions?

Thank you for your insights.

**Comment by rtheunissen** [comment]
While I'm sure there are ways to improve the performance of a `Vector` in this case, the primary advantage of using a vector is lower memory usage. Some things, like iteration, is impossible to compete with because of the way PHP treats an array as a special case internally. 

Might be interesting to see if opcache is also a factor here. (No idea)
