### ISSUE TITLE
Test failure on BigEndian

### ISSUE THREAD

**Issue by remicollet** [php-ds/extension#88]
Trying to build on PowerPC computer

```
+ /usr/bin/php -d extension=/builddir/build/BUILDROOT/php-pecl-ds-1.1.10-1.fc27.ppc64/usr/lib64/php/modules/ds.so /usr/bin/phpunit --bootstrap tests/autoload.php tests
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 549755813776 bytes) in /builddir/build/BUILD/php-pecl-ds-1.1.10/tests/tests/DequeTest.php on line 64
```

Will try to investigate (as soon as I will be able to get access to a PowerPC machine)

P.S. fails on ppc64, ok on ppc64le.

**Comment by rtheunissen** [comment]
Awesome, thank you so much for this report. For some reason I didn't see it until today. I'll investigate asap.

**Comment by rtheunissen** [comment]
@remicollet I've built php-src (7.2.0-dev NTS) and ds on `Linux debian-powerpc 3.2.0-4-powerpc #1 Debian 3.2.51-1 ppc` using QEMU on my Macbook Pro and confirmed that the system and build uses big endian.

The only test that failed was `Ds\Tests\SetTest::testArrayAccessGetByReference`, where the `E_NOTICE` wasn't thrown. This seems incredibly strange to me and I'll take a look at why that is, but it does mean that `DequeTest` didn't fail at all as it did in your environment.

`lscpu` shows:
```
Architecture: ppc
CPU op-mode(s): 32-bit
Byte Order: Big Endian
```

I wonder if 64-bit would make a difference? 

Where did you find/see this failing?

**Comment by remicollet** [comment]
@rtheunissen I see this failing running a scratch build in Fedora infrastructure (I was planning to propose this package for official repository, and discover that).

Scratch build (just launched, still running)
https://koji.fedoraproject.org/koji/taskinfo?taskID=20580847

Because of Holidays, won't be able to dig on this issue more before start of August.

**Comment by remicollet** [comment]
I was finally able to have a ppc64 server to work on this issue.
