### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by stepzerosolutions** [php-ds/extension#89]
**How to reproduce** 
Install the extension using  pecl install ds
Add extension to php.ini file using extension=ds.so
sudo apache2ctl graceful
Installation success and I can see the extension so file in extension directory.

However when I run phpinfo() I can't see any extension details in the extensions section
When I try to run simple example http://php.net/manual/en/ds.examples.php it gives me error 500
details in error.log is 

 PHP Fatal error:  Uncaught Error: Class 'Ds\\Vector' not found in /var/www/html/test.php:2\nStack trace:\n#0 {main}\n  thrown in /var/www/html/test.php on line 2

System details
Apache 2
Ubuntu 16:04

**Comment by rtheunissen** [comment]
Did you add it to the correct .ini? What does `php -m` say?

**Comment by stepzerosolutions** [comment]
It doesn't load ds.

**Comment by stepzerosolutions** [comment]
I get following error when I use php -v

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/ds.so' - /usr/lib/php/20151012/ds.so: undefined symbol: php_json_serializable_ce in Unknown on line 0

**Comment by rtheunissen** [comment]
See #2
