### ISSUE TITLE
Internal refactor to separate concerns

### ISSUE THREAD

**Issue by rtheunissen** [php-ds/extension#9]
@krakjoe we can discuss things here. Current plan:

## Files

```c
#include "[src/public/]  ds/name.h"
#include "[src/private/] ds/common.h"
#include "[src/private/] ds/php_name.h"
#include "[src/private/] ds/ce/php_name.h"
#include "[src/private/] ds/handlers/php_name.h"
#include "[src/private/] ds/iterators/php_name.h"
```

## Structs

- `ds_name_t` for the data structures
- `php_ds_name_t` for the objects

## Macros

**Internal**:
- `Z_{NAME}` 
- `Z_{NAME}_P`

**External**:
- `ZVAL_{NAME}`
- `RETURN_{NAME}`

## Policies

- Prefer index access over pointer arithmetic, ie "`&ptr[index]`" over "`ptr + index`".
- Strict 80 char max line length.
- Header functions should have comments to describe their use where not obvious.
- Function order in .c should match the order in .h
- Method entries must be in alphabetical order.
- Macros should be prefixed with `DS_` where appropriate.
- Internal functions should be prefixed with `php_ds_`
- External functions should be prefixed with `ds_`
- Headers should include everything they need to be included in isolation

**Comment by krakjoe** [comment]
looking gooood ...

**Comment by rtheunissen** [comment]
@krakjoe merged into master. It's not perfect, but so much better than it was (I think).
